# Generated by Django 3.1.3 on 2021-02-26 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CPUModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='RamSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ComputersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(max_length=200, unique=True)),
                ('date', models.DateField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_company', to='computers.brand')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpu_type', to='computers.cpumodel')),
                ('monitor_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_size', to='computers.monitorsize')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='os_type', to='computers.os')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ram_size', to='computers.ramsize')),
            ],
        ),
    ]
