# Generated by Django 3.1.3 on 2021-02-26 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('computers', '0001_initial'),
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computersmodel',
            name='squad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='squad_location', to='formations.squads'),
        ),
    ]
