# Generated by Django 3.1.3 on 2021-02-26 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wings',
            name='wing_commander',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wing_commander', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wings',
            name='wing_coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wing_coordinator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='squads',
            name='Squad_commander',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='squad_commander', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='squads',
            name='Squad_coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='squad_coordinator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='squads',
            name='wing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wing', to='formations.wings'),
        ),
    ]
